version: "3.9"

services:
  api:
    build: .
    container_name: crm_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mailhog
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  worker:
    build: .
    container_name: crm_worker
    env_file:
      - .env
    depends_on:
      - mailhog
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    command: ["python", "-m", "app.pipeline", "--file", "data/leads.csv", "--batch-size", "10", "--max-concurrent-batches", "5"]

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
